#! /bin/sh
# /etc/init.d/StartUP
#

# Some things that run always
touch /var/lock/StartUP

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script StartUP "
    sleep 10
    python /opt/send_Email_With_IP.py &
    #python /home/artur-adm/sensor/LCDtestArtur.py &
    #python /home/artur-adm/sensor/showIP.py &
    ;;
  stop)
    echo "Stopping script StartUP"
    ;;
  *)
    echo "Usage: /etc/init.d/StartUP {start|stop}"
    exit 1
    ;;
esac

exit 0
